---
title: "RNAseq_analysis"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
```

## RNAseq analysis

### Read input file and generate DESeq2 object

```{r}
library(DESeq2)
# Sample information
sample.meta = data.frame("SampleName" = c(paste0("C6",1:3),
                                          paste0("CL",1:3),
                                          paste0("WT",1:3))
                         ,"Group" = c(rep("6C",3),
                                      rep("CL",3),
                                      rep("WT",3)))
sample.meta

# count matrix
mtx = read.table("genes_expression_expected_count.tsv", sep = "\t", header = T, row.names = 1)
mtx = mtx[,-1]
df2 <- data.frame(apply(mtx, 2, function(x) round(x,0))) # round the estiminated count generated by RSEM
head(df2)

dds <- DESeqDataSetFromMatrix(countData = df2,
                              colData = sample.meta,
                              design= ~ Group)
ntd <- normTransform(dds)
vsd <- vst(dds, blind=FALSE)
```

### Heamap of Ms4a expression

```{r}
library(pheatmap)
library(RColorBrewer)
library(viridis)
select <- unique(grep("Ms4a",rownames(ntd), value = T))
p1 = pheatmap(assay(ntd)[select,grep("WT|CL",colnames(assay(ntd)))], cluster_rows=T, show_rownames=T,
             cluster_cols=T, color = brewer.pal(9, "OrRd"))
p1

p2 = pheatmap(assay(ntd)[select,grep("WT|C6",colnames(assay(ntd)))], cluster_rows=T, show_rownames=T,
             cluster_cols=T, color = brewer.pal(9, "OrRd"))
p2
```

```{r}
sessionInfo()
```
